version: '3'
services:
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    expose:
      - 5432
    ports:
      - "5432:5432"

  web:
    build: .
    tty: true
    depends_on:
      - db
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/blog_rails
    expose:
      - 3000
    ports:
      - "3000:3000"
    # env_file:
    #   - .env