version: '3'
services:
  db:
    image: postgres:12.3
    environment:
      POSTGRES_PASSWORD: "postgres"

  web:
    build: .
    tty: true
    depends_on:
      - db
    links:
      - db
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/blog_rails
    expose:
      - 3000
    ports:
      - "3000:3000"
    entrypoint:
      - "./bin/container_setup.sh"
