default: &default
  adapter: mysql2
  encoding: utf8
  reconnect: true
  pool: 10
  username: erick
  password: 123456
  host: localhost

development:
  <<: *default
  database: blog_rails_development

test:
  <<: *default
  database: blog_rails_test

production:
  <<: *default
